import{S as E,a as R,i as n}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const h=document.querySelector(".gallery"),d=document.querySelector(".loader"),g=document.querySelector(".load-more");let f;function p(o){const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:a,comments:P,downloads:q})=>`
    <li class="gallery-item">
    <a class="gallery-link" href="${s}"><img class="gallery-image"src="${i}" alt="${e}"/>
    </a>
    <div class="info">
    <p class="info-item"><b>Likes</b> ${r}</p>
    <p class="info-item"><b>Views</b> ${a}</p>
    <p class="info-item"><b>Comments</b> ${P}</p>
    <p class="info-item"><b>Downloads</b> ${q}</p>
    </div>
    </li>`).join("");h.insertAdjacentHTML("beforeend",t),f?f.refresh():f=new E(".gallery a",{captionsData:"alt",captionDelay:250})}function $(){h.innerHTML=""}function y(){d.classList.add("is-loading"),d.textContent="Loading images, please wait..."}function L(){d.classList.remove("is-loading"),d.textContent=""}function b(){g.classList.remove("hidden")}function w(){g.classList.add("hidden")}const B="49743900-b0f1cd5437de5205d7989fbc4",x="https://pixabay.com/api/",M=15;async function S(o,t=1){const i=new URLSearchParams({key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:t});try{return(await R.get(`${x}?${i}`)).data}catch(s){throw console.log(s),s}}const v=document.querySelector(".form"),H=v.querySelector('[name="search-text"]'),O=document.querySelector(".load-more");let u=1,c="",m=0,l=0;v.addEventListener("submit",async o=>{if(o.preventDefault(),c=H.value.trim(),!c){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}u=1,l=0,$(),w(),y();try{const t=await S(c,u);m=t.totalHits,t.hits.length===0?n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(p(t.hits),l+=t.hits.length,l<m&&b())}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{L()}});O.addEventListener("click",async()=>{u++,y(),w();try{const o=await S(c,u);p(o.hits),l+=o.hits.length,A(),l<m?b():n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{n.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{L()}});function A(){const o=document.querySelector(".gallery-item");if(o){const t=o.getBoundingClientRect().height;window.scrollBy({left:0,top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
