import{S as R,a as $,i as n}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const g=document.querySelector(".gallery"),d=document.querySelector(".loader"),p=document.querySelector(".load-more");let f;function y(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:a,comments:v,downloads:E})=>`
    <li class="gallery-item">
    <a class="gallery-link" href="${s}"><img class="gallery-image"src="${i}" alt="${e}"/>
    </a>
    <div class="info">
    <p class="info-item"><b>Likes</b> ${o}</p>
    <p class="info-item"><b>Views</b> ${a}</p>
    <p class="info-item"><b>Comments</b> ${v}</p>
    <p class="info-item"><b>Downloads</b> ${E}</p>
    </div>
    </li>`).join("");g.insertAdjacentHTML("beforeend",t),f?f.refresh():f=new R(".gallery a",{captionsData:"alt",captionDelay:250})}function B(){g.innerHTML=""}function L(){d.classList.add("is-loading"),d.textContent="Loading images, please wait..."}function b(){d.classList.remove("is-loading"),d.textContent=""}function w(){p.classList.remove("hidden")}function S(){p.classList.add("hidden")}const x="49743900-b0f1cd5437de5205d7989fbc4",M="https://pixabay.com/api/",H=15;async function P(r,t=1){const i=new URLSearchParams({key:x,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:H,page:t});try{return(await $.get(`${M}?${i}`)).data}catch(s){throw console.log(s),s}}const q=document.querySelector(".form"),O=q.querySelector('[name="search-text"]'),A=document.querySelector(".load-more"),h=document.querySelector(".gallery-item");let u=1,c="",m=0,l=0;q.addEventListener("submit",async r=>{if(r.preventDefault(),c=O.value.trim(),!c){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}u=1,l=0,B(),S(),L();try{const t=await P(c,u);m=t.totalHits,t.hits.length===0?n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(t.hits),l+=t.hits.length,l<m&&w())}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{b()}});A.addEventListener("click",async()=>{u++,L(),S();try{const r=await P(c,u);y(r.hits),l+=r.hits.length,_(),l<m?w():n.info({title:"End of results",message:"This is the end of the search results.",position:"topRight"})}catch{n.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{b()}});function _(){if(h){const r=h.getBoundingClientRect().height;window.scrollBy({left:0,top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
